app:
  host: 0.0.0.0
  port: 8080

log:
  debug: false
  file: /var/log/framework/framework.log

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: 123456
  database: xxxx

redis:
  host: 127.0.0.1
  port: 6379
  password: 123456
  db: 0
